<?xml version="1.0" encoding="UTF-8" ?>
<DataControlConfigs xmlns="http://xmlns.oracle.com/adfm/configuration" version="12.1.3.10.8" id="DataControls"
                    Package="pe01errorgenerichumantask">
  <AdapterDataControl id="PE01ErrorGenericHumanTask_HTE01AtenderError"
                      FactoryClass="oracle.adf.model.adapter.DataControlFactoryImpl"
                      ImplDef="oracle.bpel.services.datacontrol.XSDDataControlDefinition" SupportsTransactions="true"
                      SupportsSortCollection="false" SupportsResetState="false" SupportsRangesize="false"
                      SupportsFindMode="false" SupportsUpdates="false"
                      Definition="PE01ErrorGenericHumanTask_HTE01AtenderError"
                      BeanClass="PE01ErrorGenericHumanTask_HTE01AtenderError"
                      xmlns="http://xmlns.oracle.com/adfm/datacontrol">
    <Source>
      <XSDDataControl xmlns="http://xmlns.oracle.com/bpel/workflow/task"
                      SchemaLocation="file:/C:/Proyectos/BCIE/02-BPM-PROCESS/PE01Error/PE01ErrorProcess/SOA/Schemas/HTE01AtenderErrorWorkflowTask.xsd"
                      RootElement="task" rootelementnamespace="http://xmlns.oracle.com/bpel/workflow/task"
                      taskLoc="../PE01ErrorProcess/SOA/HumanTasks/HTE01AtenderError.task" InitiationTask="false"
                      DocumentStoreConfiguration="false"/>
    </Source>
  </AdapterDataControl>
</DataControlConfigs>
